import { BvPlugin } from 'bootstrap-vue/src'

// Plugin that installs all plugins
export declare const componentsPlugin: BvPlugin

// Export all components as named exports
export * from './alert'
export * from './avatar'
export * from './badge'
export * from './button'
export * from './button-group'
export * from './calendar'
export * from './checkbox'
export * from './datepicker'
export * from './dropdown'
export * from './file-input'
export * from './form'
export * from './icon'
export * from './input'
export * from './input-group'
export * from './modal'
export * from './nav'
export * from './popover'
export * from './progress'
export * from './radio'
export * from './range-slider'
export * from './select'
export * from './selector'
export * from './sidebar'
export * from './table'
export * from './tooltip'
